name: 'Remove unused tools from the runner'
author: 'Altan Orhon'
description: 'This action will remove the tools that are not needed for the workflow from the runner'
inputs:
  rm-android:
    description: "Whether to remove Android tools"
    default: 'true'
  rm-dotnet:
    description: "Whether to remove .NET tools"
    default: 'true'
  rm-hosted-tool-cache:
    description: "Whether to remove the hosted tool cache"
    default: 'true'
  rm-powershell:
    description: "Whether to remove PowerShell"
    default: 'true'
  rm-swift:
    description: "Whether to remove Swift"
    default: 'true'
  rm-chromium:
    description: "Whether to remove Chromium"
    default: 'true'
  rm-azure-cli:
    description: "Whether to remove Azure CLI"
    default: 'true'
  rm-apt-packages:
    description: "Remove apt packages"
    default: 'false'
  rm-apt-cache:
    description: "Clear apt cache"
    default: 'false'
  apt-packages-remove-default:
    description: "Packages to remove"
    default: 'ansible azure-cli xorriso zsync esl-erlang firefox gfortran-8 gfortran-9 google-chrome-stable google-cloud-sdk imagemagick libmagickcore-dev libmagickwand-dev libmagic-dev ant ant-optional kubectl mercurial mono-complete libmysqlclient unixodbc-dev yarn chrpath libssl-dev libxft-dev libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev snmp pollinate libpq-dev postgresql-client powershell ruby-full sphinxsearch subversion mongodb-org azure-cli microsoft-edge-stable google-cloud-sdk'
  apt-packages-remove-include:
    description: "Additional packages to remove"
  apt-packages-remove-exclude:
    description: "Packages to keep"

runs:
  using: 'composite'

  steps:
    - name: Inform of using different action
      shelL: bash
      run: |
        echo "::warning::Deprecated - delegating to easimon/maximize-build-space for this task"
    - name: Clear up space
      uses: easimon/maximize-build-space@master
      with:
          remove-dotnet: "${{ inputs.rm-dotnet }}"
          remove-android: "${{ inputs.rm-android }}"
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'